movieproject/movieproject/movieapp/urls.py
from django.conf import settings

from .import views
from django.urls import path,include
from django.conf.urls.static import static
app_name='movieapp'

urlpatterns = [

    path('',views.demo,name='demo'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

movieproject/movieproject/movieapp/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name=models.CharField(max_length=120)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

movieproject/movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','image']

movieproject/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.


def demo(request):
    context=Movie.objects.all()


    return render(request,'index.html',{'clip':context})

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc= request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,image=img)
        movie.save()

    return render(request,'add.html')


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name='name' placeholder="Enter your name">
    <input type="text" name='desc' placeholder="Enter the description">
    <input type="text" name='year' placeholder="Enter the year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

movieproject/movieproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LATEST MOVIE DETAIL STORE</a>
      <br>
  </div>
</nav>
</body>
</html>
{% block body %}
{% endblock %}

movieproject/movieproject/templates/delete.html
<form method="post">
  Are you want to delete this movie?
  <input type="submit">
</form>

movieproject/movieproject/templates/detail.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block body %}
<br>
<div class="container">
    <div class="row">
        <span class="border border-3">
        <div class="col-md-4">
            <img src="{{movie.image.url}}" width="350" height="500"><br>

        </div>
        <div class="col-md-8">
            <br>
        <br>

    {{movie.name}}<br>
            <br>
    {{movie.desc}}</span>
<br>
<br>
{{movie.year}}<br>
        <br>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>

        </span>

        </div>



        </div>
</div>




{% endblock %}


</body>
</html>

movieproject/movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}

<br>
<div class="container">
    <div class="row">
        {% for i in clip %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="400">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>

<br>



</div>


{% endblock %}